# Generated by Django 5.2.3 on 2025-06-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='cars.carcompany')),
            ],
        ),
    ]
